"""int

Revision ID: 4ca50ec1c2ab
Revises: 7082e9248dc2
Create Date: 2025-06-05 13:16:20.519482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ca50ec1c2ab'
down_revision: Union[str, None] = '7082e9248dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receipt', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('transactions', 'response_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'receipt')
    # ### end Alembic commands ###
