"""init

Revision ID: 7082e9248dc2
Revises: 60df23f6a681
Create Date: 2025-05-04 20:56:19.354962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7082e9248dc2'
down_revision: Union[str, None] = '60df23f6a681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('network_id', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=60, scale=0), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('txn_hash', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_balances_address', table_name='balances')
    op.drop_index('ix_balances_token_id', table_name='balances')
    op.drop_table('balances')
    op.add_column('networks', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'meta')
    op.create_table('balances',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=60, scale=0), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name='balances_token_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='balances_pkey')
    )
    op.create_index('ix_balances_token_id', 'balances', ['token_id'], unique=False)
    op.create_index('ix_balances_address', 'balances', ['address'], unique=False)
    op.drop_table('transactions')
    # ### end Alembic commands ###
