"""init

Revision ID: 60df23f6a681
Revises: 
Create Date: 2025-04-20 09:00:21.022126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60df23f6a681'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('native_symbol', sa.String(), nullable=False),
    sa.Column('endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('network_id', sa.String(), nullable=True),
    sa.Column('decimals', sa.SmallInteger(), nullable=True),
    sa.Column('contract', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_contract'), 'tokens', ['contract'], unique=False)
    op.create_index(op.f('ix_tokens_network_id'), 'tokens', ['network_id'], unique=False)
    op.create_index(op.f('ix_tokens_symbol'), 'tokens', ['symbol'], unique=False)
    op.create_table('balances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('token_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=60, scale=0), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balances_address'), 'balances', ['address'], unique=False)
    op.create_index(op.f('ix_balances_token_id'), 'balances', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balances_token_id'), table_name='balances')
    op.drop_index(op.f('ix_balances_address'), table_name='balances')
    op.drop_table('balances')
    op.drop_index(op.f('ix_tokens_symbol'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_network_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_contract'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('networks')
    # ### end Alembic commands ###
